app_admin/auth.py
from flask import Blueprint, request, render_template, redirect, flash, url_for, session
from werkzeug.security import check_password_hash
from app_user.models import User
from .models import Admin
from flask import current_app as app
from Main.db import db
import click
from werkzeug.security import generate_password_hash

bp = Blueprint('admin', __name__,url_prefix='/admin')


@app.cli.command('create-admin')
def create_admin():
    name = input("Admin Name: ")
    pas = input("Password: ")
    conf_pas = input("Confirm password: ")
    pswd = generate_password_hash(pas)
    while True:
        if conf_pas.strip() == pas.strip():
            break
        print("password did not match")
    email = input("email: ")
    mobile=input("Phone: ")
    
    if not name or not pas or not email:
        print('All parameters are required except phone.')
        return 

    print(f'Creating Admin for username: {name}')
    try:
        new_admin = Admin(admin_name=name, password=pswd, email=email, mobile=mobile)
        db.session.add(new_admin)
        db.session.commit()
    except:
        print("Something went wrong on the server side.")
    else:
        print(f'Successfully created admin with username: {name} and email: {email}')
@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        admin_name = request.form['username']
        password = request.form['password']
        error = None
        admin = Admin.query.filter(Admin.admin_name == admin_name).first()
        if admin:
            user = User.query.filter(User.username==admin.admin_name).first()
        if admin is None:
            error = 'Incorrect Username.'
        elif not check_password_hash(admin.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['admin_name'] = admin.admin_name
            if user is not None:
                session['user_id'] = user.user_id
            session['admin_id'] = admin.admin_id
            session.modified = True
            flash(f"Successfully logged in for Admin: {admin.admin_name}", 'info')
            return redirect(url_for('admin_crud.dashboard'))

        flash(error, 'error')
        
        # debugging 
        print(error)

    return render_template('admin/admin_login.html')

@bp.route('/logout')
def logout():
    session.pop('admin_id', None)
    session.pop('admin_name', None)
    session.modified= True
    flash('You were logged out!', 'info')
    return redirect(url_for('admin.login'))

app_show_manager/routes.py
from flask import Blueprint, request, render_template, redirect, flash, url_for, session
from .models import Venue, Show,Bookings, ShowSearch, SearchCity, Tags
from app_user.models import User 
from Main.config import login_required
from flask import current_app as app
from Main.db import db

from datetime import datetime

bp = Blueprint('show_manager', __name__, url_prefix='')


@bp.route("/", methods=["GET", "POST"])
def home():
    try:
        venues = Venue.query.all()
        # tuple of (start_time, end_time, show_id, show.title, show.ticket_price, s.fill_count, venue_id, v.name, v.place,v.capacity, show.rating)
        # _________(___0______,____1____,____2____,____3_____,_______4________,_______5________,____6___,____7____,___8____,___9____,____10_____)
        shows = []
        qtags = Tags.query.all()
        tags=set()
        for t in qtags:
            print(t.tag)
            tags.add(t.tag.lower().strip())
        for v in venues:
            for s in v.shows:
                if str(datetime.now()) <= s.start_time:
                    shows.append((s.start_time,s.end_time, s.show_id, s.title, s.ticket_price, s.fill_count , v.venue_id, v.name, v.place, v.capacity, s.rating))
        shows.sort(reverse=True)
    except:
        flash("Oops! something went wrong!", 'error')
        return redirect(url_for('show_manager.home'))
    return render_template('index.html', venues=venues, shows=shows, tags=tags)



@bp.route("/genere_wise", methods=["GET", "POST"])
def genre_wise():
    if request.method == "POST":
        try:
            sel_tags = request.form.getlist('tag')
            sel_tags = [t.strip().lower() for t in sel_tags]
            venues = Venue.query.all()
            shows = []
            ids = []
            for t in sel_tags:
                tag = Tags.query.filter(Tags.tag.like(t.strip())).all()
                for e in tag:
                    ids.append(e.show_id)
                print('got t')
            ids = set(ids)
            for id in ids:
                shows.append(Show.query.filter(Show.show_id==id).first())
                
        except:
            flash("No shows with given genre", 'info')
            # return redirect(url_for("show_manager.home"))
        return render_template('user/genre_wise.html', sel_tags=sel_tags, shows= shows, venues=venues)


@bp.route("/bookings/<int:user_id>/", methods=["GET", "POST"])
@login_required
def user_bookings(user_id):
    bookings = Bookings.query.filter(Bookings.user_id==user_id).order_by(Bookings.num_seats).all()
    return render_template('user/bookings.html', bookings=bookings)






@bp.route("booking/<int:venue_id>/<int:show_id>/", methods=["GET", "POST"])
@login_required
def create_booking(venue_id, show_id):
    venue = Venue.query.filter( Venue.venue_id == venue_id).first()
    show = Show.query.filter(Show.show_id==show_id).first()
    if request.method=='POST':
        show = Show.query.filter(Show.show_id==show_id).first()
        num_seats = int(request.form.get('number'))
        user_id = session.get('user_id')
        bookings = Bookings.query.filter(Bookings.venue_id==venue_id, Bookings.show_id==show_id, Bookings.user_id==user_id).all()
        error = ''
        try:
            if (show.fill_count + num_seats) <= venue.capacity:
                if len(list(bookings)) != 0:
                    print(bookings[0].venue_name)
                    bookings[0].num_seats += num_seats
                    db.session.commit()
                else:
                    new_booking = Bookings(user_id=user_id, venue_id=venue_id,
                                           venue_name=venue.name, show_id=show_id,
                                           show_title=show.title, num_seats=num_seats)
                    db.session.add(new_booking)
                    db.session.commit()
                show.fill_count += int(num_seats)
                db.session.commit()
                flash(f'successfully booked {num_seats} tickets for show {show.title}', 'success')
                return redirect(url_for('show_manager.home'))
            else:
                flash('Number of seats can\'t be more than available seats!', 'danger')
                return redirect(url_for('request.url'))
        except :
            error = "Seats already occupied"
    return render_template('user/book_ticket.html', show=show, venue=venue)

@bp.route('/venue/<int:venue_id>', methods=["GET", "POST"])
def venue_wise(venue_id):
    try:
        venue = Venue.query.filter(Venue.venue_id==venue_id).first()
        shows = venue.shows
    except:
        flash("Oops! something went wrong!", "warning")
        return redirect(url_for('show_manager.home'))
    return render_template('user/venue_wise.html', venue=venue, shows=shows)

@bp.route('/rate/<int:user_id>/<int:show_id>', methods=["GET", "POST"])
@login_required
def rate(user_id, show_id):
    
    try:
        user_book= Bookings.query.filter(Bookings.user_id==user_id, Bookings.show_id==show_id).first()
        if not user_book:
            flash("No bookings for the user to rate!", 'warning')
            return redirect(url_for('show_manager.home'))
        if request.method=="POST":
            rating = request.form['rating']
            show = Show.query.filter(Show.show_id==show_id).first()
            user_book= Bookings.query.filter(Bookings.user_id==user_id, Bookings.show_id==show_id).first()
            print(user_book.venue_name, user_book.show_title)
            user_book.user_rating = float(rating)
            db.session.commit()
            rating = Bookings.query.filter(Bookings.show_id==show_id).all()
            if rating:
                n = len(rating)
                total = 0
                for r in rating:
                    total += r.user_rating
                avg = total/n
                show.rating = avg
                db.session.commit()
            flash("Rated the show successfully!", "info")
            return redirect(url_for('show_manager.user_bookings', user_id=user_id))
    except:
        print("rated Failed ------------")
        flash("Oops! something went wrong!", "warning")
        return redirect(url_for('show_manager.rate', user_id=user_book.user_id, show_id=user_book.show_id))
    return render_template('user/rate.html', user_book=user_book)


@bp.route('/show_details/<int:show_id>', methods=["GET"])
def show_details(show_id):
    try:
        show = Show.query.filter(Show.show_id == show_id).first()
        venue = None
        if show is not None:
            venue = Venue.query.filter(Venue.venue_id == show.venue_id).first()
    except:
        flash("Oops! something went wrong")
        return redirect(url_for("show_manager.home"))
    return render_template('show_details.html', show=show, venue=venue)



@bp.route('/search', methods=["GET"])
def search():
    q = request.args.get('q')
    results = []
    city_result = []
    cities = []

    try:
        if q:
            sh_query = db.session.query(ShowSearch).filter(
                ShowSearch.title.op("MATCH")(q)).all()
        v_query = db.session.query(SearchCity).filter(
            SearchCity.name.op("MATCH")(q)).all()

        c_query = db.session.query(SearchCity).filter(
            SearchCity.place.op("MATCH")(q)).all()

        if v_query is not None:
            for v in v_query:
                city_result.extend(Venue.query.filter(
                    Venue.venue_id == v.venue_id).all())

        if c_query is not None:
            for c in c_query:
                city_result.extend(Venue.query.filter(
                    Venue.venue_id == c.venue_id))

        if sh_query is not None:
            for s in sh_query:
                results.extend(Show.query.filter(Show.show_id == s.show_id))
    except:
        flash("oops, something went wrong!", 'danger')
        return redirect(url_for('show_manager.home'))
    return render_template('results.html', results=results, city_wise=city_result, q=q)

app_user/auth.py
from flask import Blueprint, request, render_template, redirect, flash, url_for, session, g
from werkzeug.security import check_password_hash, generate_password_hash
from app_user.models import User

from sqlalchemy.exc import IntegrityError
from functools import wraps
from flask import session, redirect, url_for,g
from Main.db import db

bp = Blueprint('auth', __name__,url_prefix='/auth')

# def login_required(original):
#     @wraps(original)
#     def wrapper_function(*args, **kwargs):
#         print(session['username'])
#         if g.user is None:
#             return redirect(url_for('auth.login'))
#         else:
#             return original(*args, **kwargs)
#     return wrapper_function




@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        mobile = request.form['mob']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif not email:
            error = "email is required"


        if error is None:
            try:
                new_user = User(username=username, password=generate_password_hash(password), email=email, mobile=mobile)
                db.session.add(new_user)
                db.session.commit()
            except AttributeError:
                error = f"User {username} is already registered."
                return redirect(url_for("auth.register"))

            else:
                flash(f'Created account for {username}!', 'success')
                return redirect(url_for("auth.login"))

        flash(error)

        # debugging
        print(error)
        
    return render_template('user/user_register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user = User.query.filter(User.username == username).first()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['username'] = user.username
            session['user_id'] = user.user_id
            session.modified = True
            return redirect(url_for('show_manager.home'))

        flash(error)
        
        # debugging 
        print(error)

    return render_template('user/user_login.html')

@bp.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('username', None)
    session.modified= True
    return redirect(url_for('show_manager.home'))

templates/abase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block script %}
    {% endblock script %}
    <title>Admin Dashboard</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for cat, msg in messages %}
    <div class="alert alert-{{cat}} alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith%}
    <div class="container-fluid  text-center">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <h1 class="navbar-brand">Ticket Wala</h1>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-even">
                    {% if session['admin_name'] and session['admin_id'] %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('admin_crud.dashboard')}}">Dashboard</a>
                    </li>

                    <li class="nav-item"><a class="nav-link" href="{{ url_for('admin_crud.summary')}}">Statistics</a>
                    <li class="nav-item nav-link">Admin: <span>{{ session['admin_name'] }}</span></li>
                    </li>

                    <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.logout')}}">Log Out</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.login')}}">Admin Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

    {% block content %}

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>


</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block script %}
    {% endblock script %}
    <title>Ticket Wala| Book tickets Online</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for cat, msg in messages %}
    <div class="alert alert-{{cat}} alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith%}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid row">
            <div class="col-md-2 col">
                <a class="navbar-brand" href="{{url_for('show_manager.home')}}">Ticket Wala</a>
            </div>
            <div class="col-2 d-md-none d-block">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="col-md-1">
                <li class="nav-item nav-link"><a href="{{url_for('show_manager.home')}}" class="nav-link">Home</a>
                </li>
            </div>
            <div class="col-md-auto d-md-block d-inline">
                <form class="d-flex" action="/search" method="get">
                    <input class="form-control me-2" type="text" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
            <div class="col-md-4">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if session['username'] and session['user_id'] %}
                        <li class="nav-item nav-link">{{ session['username'] }}
                        <li class="nav-item"><a class="nav-link"
                                href="{{ url_for('show_manager.user_bookings', user_id=session['user_id'])}}">Bookings</a>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout')}}">Log Out</a>
                            {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register')}}">Register</a>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login')}}">Log In</a>
                            {% endif %}
                    </ul>
                </div>
            </div>

        </div>
    </nav>

    {% block content %}

    {% endblock content %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>


</body>

</html>

templates/error.html
{%extends './base.html' %}

{% block content %}
<h1>something went wrong</h1>
<a href="{{url_for('show_manager.home')}}"> Go to HomePage </a>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}


<div class="row ps-2">
    <div class="col-md-2">
        <div class="card p-3 mt-5">
            <div class="row">
                <div class="col-12">
                    <h5>Genres</h5>
                    <form action="{{url_for('show_manager.genre_wise')}}" method="post"><input
                            class="btn btn-sm btn-outline-info" type="submit" value="Apply">
                        <ul class="d-grid g-1">
                            {% for t in tags %}
                            {% if t %}
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="tag" type="checkbox" id="{{t.lower()}}"
                                    value="{{t.lower()}}">
                                <label class="form-check-label" for="{{t}}">{{t|upper}}</label>
                            </div>
                            {%endif%}
                            {% endfor %}
                    </form>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h5>Venues: </h5>
                    <ul class="d-grid g-1">
                        {% for v in venues %}
                        <a href="{{url_for('show_manager.venue_wise', venue_id=v.venue_id)}}">{{v.name}}</a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-10 px-3 mt-2">
        <h5 class="text-center">
            All venues and shows
        </h5>
        <div class="container">
            <div class="row my-3 gap-2">
                {% for s in shows %}
                <div class="col-md-3 col-sm-2 col-12">
                    <a href="{{url_for('show_manager.show_details', show_id = s[2])}}"
                        style="text-decoration:none;color:inherit">
                        <div class="card">
                            <img src="../static/img/show_thumbnails/{{s[2]}}.jpg" class="card-img-top"
                                alt="No thumbnail" width="80px" height="300px">
                            <div class="card-body">
                                <h5 class="card-title">{{s[3]}}</h5>
                                <p>Venue: {{s[7]}}, {{s[8]}}</p>
                                <p>Price: {{ s[4]}}</p>
                                <p>Rating: {{s[10]}}/5</p>
                                {% if s[5] >= s[9] %}
                                <p class="btn btn-secondary btn-sm">Housefull</p>
                                {% else%}
                                <a href="{{url_for('show_manager.show_details', show_id=s[2])}}" type="button"
                                    class="btn btn-warning">Book</a>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/results.html
{% extends './base.html'%}

{% block content%}

<div class="container">
    <h1>Showing Results for {{ q }}</h1>
    {% if results|length != 0 %}
    {% for res in results %}
    <div class="row text-center">

        <p><a href="{{ url_for('show_manager.show_details', show_id=res.show_id)}}">{{res.title}}</a></p>

    </div>
    {% endfor %}
    {%else%}
    {% endif%}

</div>

{% if city_wise|length != 0 %}
<div class="container">
    {% for c in city_wise %}
    <div class="row">
        <p><a href="{{ url_for('show_manager.venue_wise', venue_id=c.venue_id)}}">{{ c.name }}</a></p>
        <p>{{ c.place }}</p>
    </div>
    <hr>
    {% endfor%}
</div>
{% endif %}

{% endblock content%}

templates/show_details.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
    <div class="row gap-2">
        <div class="col-4">
            <img src="../static/img/show_thumbnails/{{show.show_id}}.jpg" alt="Show Thumbnail">
        </div>
        <div class="col-6">
            <h1>{{show.title}}</h1>
            <p>{{show.description}}</p>
            <div class="d-grid">
                <p class="btn btn-sm btn-outline-info">{{ show.start_time[-5:]}}</p>
                <p class="btn btn-sm btn-outline-info">{{show.end_time[-5:]}}</p>
            </div>
            <h4>City = {{venue.place}} | Theatre: {{ venue.name}} </h4>
            {% if show.fill_count >= venue.capacity %}
            <p class="btn btn-secondary btn-sm">Housefull</p>
            {% else%}
            <a href="{{url_for('show_manager.create_booking', venue_id=show.venue_id, show_id=show.show_id)}}"
                type="button" class="btn btn-warning">Book</a>
            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}